### ISSUE TITLE
model diagnostic Tables

### ISSUE THREAD

**Issue by jaclyncleary** [grinnellm/HerringAssess#6]
Add from 2017 Res Doc to SR "Appendix":
Tables 3-7
Tables 13-17

**Comment by grinnellm** [comment]
@cgrandin I am getting an error with the Reference points tables (13 to 17 in the res-doc):
![image](https://user-images.githubusercontent.com/25674027/46224522-759bc700-c30b-11e8-8709-3b42aec2807b.png)
I found your code in the res-doc (in `7_tables.rnw`):
-----------------
<<hg.ref.points.table, results='asis', echo=FALSE>>=
cap <- paste0("Posterior (5\\textsuperscript{th} percentile, Median, and ",
              "95\\textsuperscript{th} percentile) of proposed reference ",
              "points for the Haida Gwaii models. Biomass numbers are in ",
              "thousands of tonnes.")
make.ref.points.table(hg.b,
                      # hg.am1,
                      xcaption = cap,
                      xlabel = "tab:hg-ref-points",
                      font.size = 11,
                      space.size = 12,
                      placement = "H")
@
-------------------
I commented out the line that refers to `hg.am1` since we no longer run this model. But I get this error:
`#> Error in make.ref.points.table(hg.b, xcaption = cap, xlabel =
"tab:hg-ref-points", : argument "model.am1" is missing, with no default`

**Comment by cgrandin** [comment]
That's due to the function itself needing two models. I can fix this

**Comment by cgrandin** [comment]
I fixed them in commit 844824a23d6af1896971e86fe3f77f1d91098415

**Comment by grinnellm** [comment]
Awesome, thanks @cgrandin!
